env:
  browser: true
  es2021: true
extends: airbnb-base/legacy
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  "no-unused-vars": "off",
  quotes: off,
  "class-methods-use-this": "off",
}
